include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gr.dart"
    - "**/generated/**"
  language:
    strict-casts: false
    strict-inference: false
    strict-raw-types: false

linter:
  rules:
    # Essential Error Prevention
    - avoid_print
    - cancel_subscriptions
    - close_sinks
    - unawaited_futures
    - use_build_context_synchronously

    # Code Quality
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - prefer_final_locals
    - prefer_single_quotes
    - sort_child_properties_last
    - use_key_in_widget_constructors

    # Flutter Specific
    - sized_box_for_whitespace
    - avoid_unnecessary_containers
    - use_colored_box
    - use_decorated_box
